"use client";

import { useEffect, useState } from "react";
import { ChevronRight, Trophy, UserRound } from "lucide-react";

type RankUser={displayName:string;xp:number};
type LearningData={profile?:RankUser&{email?:string};ranking?:RankUser[]};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"U";

function useRanking(){const[data,setData]=useState<LearningData|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/learning").then(r=>r.ok?r.json():null).then(value=>setData(value)).catch(()=>setData(null)).finally(()=>setLoading(false))},[]);return{data,loading}}

export function HomeRankCard({open}:{open:()=>void}){const{data,loading}=useRanking(),list=data?.ranking||[],me=data?.profile,position=me?list.findIndex(user=>user.displayName===me.displayName)+1:0;return <section className="rank-card live-rank"><header className="section-title"><span><small>RANKING REAL</small><h3>{loading?"Carregando classificação...":position?`Sua posição: ${position}º`:"Ranking ainda sem participantes"}</h3></span><button onClick={open}>Ver ranking</button></header>{list.length?<div>{list.slice(0,3).map((user,index)=><span key={`${user.displayName}-${index}`} className={user.displayName===me?.displayName?"me":""}><b>{index+1}</b><i>{initials(user.displayName)}</i><small>{user.xp.toLocaleString()} XP</small></span>)}</div>:!loading&&<div className="mini-empty"><UserRound/><p>O ranking será formado somente por usuários que realmente acessarem e pontuarem no app.</p></div>}</section>}

export default function RankingExperience({go}:{go:(screen:"profile"|"home")=>void}){const{data,loading}=useRanking(),list=data?.ranking||[],me=data?.profile;return <div className="page"><header className="top"><div><small>CLASSIFICAÇÃO DOS USUÁRIOS</small><h2>Ranking real</h2></div><div><button className="avatar" onClick={()=>go("profile")}>{me?initials(me.displayName):"—"}</button></div></header><div className="ranking live-ranking"><header><small>ATUALIZADO PELO APP</small><h1>Somente usuários cadastrados aparecem aqui.</h1><p>O XP é somado a partir dos simulados concluídos.</p></header>{loading?<div className="ranking-loading"><i/><p>Carregando usuários cadastrados...</p></div>:list.length?<><div className={`podium count-${Math.min(3,list.length)}`}>{list.slice(0,3).map((user,index)=><span key={user.displayName} className={`p${index+1}`}><i>{initials(user.displayName)}</i><b>{user.displayName.split(" ")[0]}</b><small>{user.xp.toLocaleString()} XP</small><em>{index+1}</em></span>)}</div><div className="rank-list">{list.map((user,index)=><span key={`${user.displayName}-${index}`} className={user.displayName===me?.displayName?"me":""}><b>{index+1}</b><i>{initials(user.displayName)}</i><em>{user.displayName}<small>{user.displayName===me?.displayName?"Seu perfil":"Usuário cadastrado"}</small></em><strong>{user.xp.toLocaleString()} XP</strong></span>)}</div></>:<div className="ranking-empty"><Trophy/><h2>O ranking começará com o primeiro usuário.</h2><p>Assim que alguém concluir um simulado, a classificação será criada com dados reais.</p><button onClick={()=>go("home")}>Voltar ao início <ChevronRight/></button></div>}</div></div>}
